[[redirects]]
  from = "/api/*"
  to = "https://api.peti.pt/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
